version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages
    ports:
      - 5436:5432

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  app:
    build: .
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      KAFKA_BROKER: ${KAFKA_BROKER}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db
      - kafka
