version: '3.8'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  app:
    build: .
    environment:
      POSTGRES_DSN: "host=db user=user password=password dbname=messages port=5432 sslmode=disable"
      KAFKA_BROKER: "kafka:9092"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka

volumes:
  db_data: